config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    collection {post :import}
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      # 勤怠変更申請
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month' 
  
   
    end
    collection do
      get 'index_attendance'
    end
    resources :attendances, only: :update do
    member do
        # 残業申請モーダル
        get 'edit_overwork_request'
        patch 'update_overwork_request'
    end
  end
end
  
    resources :bases do
    end
  
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true  
  validates :department, length: { in: 2..30 }, allow_blank: true
  validates :employee_number, length: { in: 1..4 }, allow_blank: true
  validates :card, length: { in: 1..4 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
   # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
    # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  #importメソッド
def self.import(file)
  CSV.foreach(file.path, headers: true) do |row|
    # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
    user = find_by(id: row["id"]) || new
    # CSVからデータを取得し、設定する
    user.attributes = row.to_hash.slice(*updatable_attributes)
    user.save
  end
end

# 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "department", "code", "uid", "basic_time", "basic_start_time", "basic_finish_time", "superior", "admin", "password"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :admin_or_correct_user, only: [:show, :edit, :update]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: :show
  
  

  def index
    @users = User.paginate(page: params[:page])
    # @users = @users.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
   @user = User.new
  end
  
  
  def import
    if params[:file].blank?
      flash[:danger] = "ファイルを選択してください。"
      redirect_to users_url
    else
    User.import(params[:file])
    flash[:success] = "ファイルをインポートしました。"
    redirect_to users_url
    end
  end

  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to index
    else
      render :edit      
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  def admin_or_correct_user
    @user = User.find(params[:id])
    unless current_user?(@user) || current_user.admin?
      flash[:danger]="権限がありません"
      redirect_to(root_url)
    end
  end
  
  def index_attendance
    @users = User.all.includes(:attendances)
  end
  
  def base
  end
  

  private

    def user_params
      params.require(:user).permit(:name, :email, :department,  :password, :password_confirmation, :employee_number, :card,
                                   :basic_time, :designated_work_start_time, :designated_work_end_time,)
    end

    def basic_info_params
      params.require(:user).permit(:department, :employee_number, :card, :designated_work_start_time, :designated_work_end_time, :basic_time, :work_time)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_form2.html.erb
<%= form_with(model: user, local: true) do |f| %>
<%= render 'shared/error_messages', object: user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>
  
  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :employee_number, class: "form-control" %>
  
  <%= f.label :card, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :card, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_time, class: "form-control" %>

  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>
  
  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %><br>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>
<br>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form'%>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<!--<div class="modal-dialog modal-lg modal-dialog-center">-->
<!--  <div class="modal-content">-->
<!--    <div class="modal-header">-->
<!--      <button type="button" class="close" data-dismiss="modal" aria-label="Close">-->
<!--        <span aria-hidden="true">×</span>-->
      <!--</button>-->
      <!--<h1 class="modal-title">基本情報の修正</h1>-->
      <h1>基本情報の修正</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <!--<%= f.label :name, class: "label-#{yield(:class_text)}" %>-->
            <!--<p><%= @user.name %></p>-->

            <!--<%= f.label :department, class: "label-#{yield(:class_text)}" %>-->
            <!--<%= f.text_field :department, class: "form-control" %>-->

            <!--<%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>-->
            <!--<%= f.time_field :basic_time, class: "form-control" %>-->

            <!--<%= f.label :work_time, class: "label-#{yield(:class_text)}" %>-->
            <!--<%= f.time_field :work_time, class: "form-control" %>-->

            <!--<div class="center">-->
            <!--  <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>-->
              <!--<button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">-->
              <!--  キャンセル-->
              <!--</button>-->
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<% provide(:class_text, 'All Users') %>
<% provide(:button_text, '編集する') %>


<h1>ユーザー一覧</h1>

<%= form_tag import_users_path, multipart: true do %>
  <%= file_field_tag :file %><br>
  <%= submit_tag "CSVをインポート" , class: "btn btn-primary"%>
<% end %>


<div class="col-md-10 col-md-offset-1">
  <%= will_paginate %><br>

    <% @users.each do |user| %>
      <tr>
        <td class="left">
          <% if current_user.admin? && !current_user?(user) %>
           <%= user.name %><br>
           |
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" }, class: "btn btn-primary" %><br>
            <div class="jumbotron">
              <button type="button" class="btn btn-primary btn-lg" data-toggle="collapse" 
              data-target="#collapseExample<%= user.id %>" aria-expanded="false" aria-controls="collapseExample">
               編集
              </button>
            </div>
          　</p>
          <div class="collapse" id="collapseExample<%= user.id %>">
            <div class="card card-body">
              <%= render 'form2', user: user %>
            </div>
          </div>

            
          <% end %>
        </td>
      </tr>
    <% end %>
  <%= will_paginate %>
</div>

app/views/users/index_attendance.html.erb
<% provide(:title, 'Attendant employees') %>

<h1>出勤中社員一覧</h1>

<table class="table table-bordered table-hover attendance-table">
  <tr>
      <td>社員番号</td>
      <td>名前</td>
  </tr>
  
  
  <tbody>
      <% @users.each do |user| %>
        <% user.attendances.each do |attendance| %>
          <% if (Date.current == attendance.worked_on) && attendance.started_at != nil && attendance.finished_at == nil %>
        <tr>
          <td><%= user.employee_number %></td>
          <td><%= user.name %></td>
        </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>
        <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-primary" %>
        【<%= l(@first_day, format: :middle) %>】勤怠管理表
        <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-primary" %>
      </td>
      <td>
        指定勤務開始時間：<%= format_basic_info(@user.designated_work_start_time) %><br>
        指定勤務終了時間：<%= format_basic_info(@user.designated_work_end_time) %>
      </td>
      <td colspan="3">基本時間：<%= format_basic_info(@user.basic_time) %></td>
      <td>月初日：<%= l(@first_day, format: :short) %></td>
    </tr>
    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>名前：<%= @user.name %></td>
      <td>コード</td>
      <td><%= @user.card.present? ? @user.card : "" %></td>
      <td>出勤日数 : <%= @worked_sum %>日</td>
      <td>月末日：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>
<div class="btn-users-show">
  
  <%= link_to"[所属長承認申請のお知らせ]" %><br>
  <%= link_to"[勤怠変更申請のお知らせ]" %><br>
  <%= link_to"[残業申請のお知らせ]" %><br>
  
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
  <%= link_to "CSV出力", "#", class: "btn btn-primary" %>
  <p><%= link_to "勤怠修正ログ(承認済)", "#", class: "btn btn-primary" %></p>
  
</div>
<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th colspan="3"></th>
        <th colspan="8">[実績]</th>
        <th colspan="5">所定外勤務</th>
      </tr>
      <tr>
        <th rowspan="2">残業申請</th>
        <th rowspan="2">日付</th>
        <th rowspan="2">曜日</th>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |day| %>
  <tr>
    <td><%= link_to "残業申請", edit_overwork_request_user_attendance_path(@user,day), remote: true, class: "btn btn-primary" %></td>
    <td><%= l(day.worked_on, format: :short) %></td>
    <td class='<%= "wday#{day.worked_on.wday}"%>'><%= $days_of_the_week[day.worked_on.wday] %></td>
    <td><%= format_hour(day.started_at) if day.started_at.present? %></td>
    <td><%= format_min(day.started_at) if day.started_at.present? %></td>
    <td>
      <% if btn_text = attendance_state(day) %>
        <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
      <% end %>
    </td>
    
    <td><%= format_hour(day.finished_at) if day.finished_at.present? %></td>
    <td><%= format_min(day.finished_at) if day.finished_at.present? %></td>
    <td></td>
    <td>
      <% if day.started_at.present? && day.finished_at.present? %>
        <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes)) %>
        <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
      <% end %>
    </td>
    <td><%= day.note %></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<% end %>
    </tbody>
    
    <tfoot>
      <!--rowspan:縦結合、colspan：横結合-->
      <tr>
        <td colspan="2">累計日数</td>
        <td colspan="7">総合勤務時間</td>
        <td colspan="1">累計在社時間</td>
        <td rowspan="2"></td>
        <td rowspan="2"></td>
        <td rowspan="2"></td>
        <td rowspan="2"></td>
        <td rowspan="2"></td>
        <td rowspan="2">所属長承認　未<br>
            <%= form_with model: @hoge, local: true, method: :patch do |f| %>

     <!--# 以下の一行がプルダウンを実装するためのコード（追記部分）-->
     <!--<%= f.select :保存先のカラム名, [["選択肢１", "実際にDBに保存させる内容"], ["選択肢２", "実際にDBに保存させる内容"]], include_blank: "選択して下さい" %>-->
     <%= f.select :保存先のカラム名, [["上長A", "上長A"], ["上長B", "上長B"]], include_blank: "選択して下さい" %>
     
     <%= f.submit "申請", class: "btn btn-primary" %>
  <% end %>
        </td>
      </tr>
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="7"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td colspan="1"><%= format("%.2f", @total_working_times.to_f) %></td>
        
      </tr>
    </tfoot>    
  </table>
</div>

<!--モーダルウインドウ-->

  <!--[残業申請モーダル]-->
  <div id="edit-overwork-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>